Repository galacticcouncil/polkalert, pull requests merged in 2019-11, with the labels that each got.

#18 Node connection awareness
  .prettierrc
  README.md
  packages/client/src/App.tsx
  packages/client/src/apollo/queries/GetNodeInfo.ts
  packages/client/src/apollo/queries/index.ts
  packages/client/src/pages/SelectApi/SelectApi.tsx
  packages/client/src/pages/Staking/Staking.tsx
  packages/client/yarn.lock
Labels: bug, chore, enhancement

#20 Settings screen added
  .prettierrc
  README.md
  eslintrc.js
  packages/client/README.md
  packages/client/blueprints/README.md
  packages/client/public/icons/hide.svg
  packages/client/public/icons/refresh.svg
  packages/client/public/icons/show.svg
  packages/client/src/App.tsx
  packages/client/src/apollo/mutations/ConnectMutation.ts
  packages/client/src/apollo/mutations/ConnectToApi.ts
  packages/client/src/apollo/mutations/UpdateSettingsMutation.ts
  packages/client/src/apollo/mutations/index.ts
  packages/client/src/apollo/queries/GetHeaders.ts
  packages/client/src/apollo/queries/GetNodeInfoQuery.ts
  packages/client/src/apollo/queries/GetSettingsQuery.ts
  packages/client/src/apollo/queries/GetValidatorsQuery.ts
  packages/client/src/apollo/queries/index.ts
  packages/client/src/layouts/DefaultLayout/DefaultLayout.tsx
  packages/client/src/pages/Contact/Contact.tsx
  packages/client/src/pages/Contact/styled.ts
  packages/client/src/pages/SelectApi/SelectApi.tsx
  packages/client/src/pages/Settings/Settings.tsx
  packages/client/src/pages/Settings/index.ts
  packages/client/src/pages/Settings/styled.ts
  packages/client/src/pages/Staking/Staking.tsx
  packages/client/src/pages/index.ts
  packages/client/src/ui/Input/Input.tsx
  packages/client/src/ui/Input/styled.ts
  packages/client/src/ui/PageTitle/PageTitle.tsx
  packages/client/src/ui/PageTitle/index.ts
  packages/client/src/ui/PageTitle/styled.ts
  packages/client/src/ui/index.ts
  packages/client/tsconfig.json
  packages/server/.gitignore
  packages/server/docker-compose.default.yml
  packages/server/ormconfig.default.json
  packages/server/package.json
  packages/server/server-config.default.json
  packages/server/src/index.ts
  packages/server/src/resolver/index.ts
  packages/server/src/schema/index.ts
  packages/server/src/settings/index.ts
  packages/server/tsconfig.json
  packages/server/yarn.lock
  setup.js
Labels: enhancement

#19 webhook mechanism added, webhook persistence alteration required
  package.json
  packages/server/server-config.default.json
  packages/server/src/resolver/index.ts
  packages/server/src/schema/index.ts
  packages/server/src/settings/index.ts
  packages/server/src/webhooks/index.ts
  yarn.lock
Labels: enhancement

#24 Client build improved, Demo added to SelectApi options
  packages/client/src/index.html
  packages/client/src/pages/SelectApi/SelectApi.tsx
  packages/client/webpack.config.js
Labels: enhancement

#29 updated README for general description
  README.md
Labels: enhancement

#31 Current/Previous eras validators split into 2 separate screens
  lerna.json
  packages/client/blueprints/story/__pascalCase_name__/__pascalCase_name__.stories.tsx
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/apollo/queries/GetValidatorsQuery.ts
  packages/client/src/components/ValidatorCard/ValidatorCard.tsx
  packages/client/src/components/ValidatorCard/styled.ts
  packages/client/src/layouts/DefaultLayout/DefaultLayout.tsx
  packages/client/src/mocks/staking.ts
  packages/client/src/pages/SelectApi/SelectApi.tsx
  packages/client/src/pages/Staking/Staking.tsx
  packages/client/src/pages/Staking/components/ValidatorList/ValidatorList.tsx
  packages/client/src/pages/Staking/components/ValidatorList/index.ts
  packages/client/src/pages/Staking/components/ValidatorList/styled.ts
  packages/client/src/pages/Staking/components/index.ts
  packages/client/src/pages/Staking/styled.ts
  packages/client/src/types/index.ts
  packages/client/src/types/router.ts
  packages/client/src/types/validator.ts
  packages/client/src/ui/Identicon/Identicon.tsx
  packages/client/src/ui/Identicon/styled.ts
  packages/client/src/ui/Tabs/Tabs.tsx
  packages/client/src/ui/Tabs/index.ts
  packages/client/src/ui/Tabs/styled.ts
  packages/client/src/ui/index.ts
  packages/client/stories/components/ValidatorCard/ValidatorCard.stories.tsx
  packages/client/stories/ui/Identicon/Identicon.stories.tsx
  packages/client/stories/ui/Tabs/Tabs.stories.tsx
  packages/server/package.json
Labels: enhancement

#33 Data loading in Settings and Staking fixed
  packages/client/src/pages/Settings/Settings.tsx
  packages/client/src/pages/Staking/Staking.tsx
Labels: bug

#34 ZeePrime logo moved under the Contact page title
  packages/client/src/pages/Contact/Contact.tsx
  packages/client/src/pages/Contact/styled.ts
Labels: enhancement
